import Navbar from "@/components/navbar/page";
import "./globals.css";
import { Roboto } from "next/font/google";
import Footer from "@/components/footer/page";

const inter = Roboto({ subsets: ["latin-ext"], weight: ["900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Navbar />
        {children} <Footer />
      </body>
    </html>
  );
}
